version: '3.3'
services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: emreddit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root  # $POSTGRES_PASSWORD  # Replace with your desired password
    ports:
      - "6000:5432"
    volumes:
      - ./dbdir:/db
  